### ISSUE TITLE
Fixed mapsize, clusters?

### ISSUE THREAD

**Issue by westwinnd** [nornagon/cdda-edit#1]
Greetings. Works great.
Probably not an issue - but size of template is (by my first look) fixed,so one cannot append it, while choosing a [NewFile], in YourApp. 

Dunno if it's internal case, or just comes from outside, from DDA. HOVERER, harvesting and quicklooking at a mansion.json from DDA sources tells me, that the size of "cluster" is fixed to 24x24 chars. Well, ok. Probably got an answer.

Edit: Yeah, ive learned, there are clusters 24x24.

**Comment by nornagon** [comment]
Hi, thanks for the comment! Yeah, currently there's a lot of extra work you need to do to get a map item that's bigger than 24x24, which cdda-edit doesn't support.
